### ISSUE TITLE
Src -> GoldSrc conversion

### ISSUE THREAD

**Issue by BlackPhrase** [headcrab-garage/OpenGS#83]
* tier0/commandline -> vstdlib/commandline
* tier1/KeyValues -> public/KeyValues
* tier1/strtools -> vstdlib/strtools

**Comment by Sh1ft0x0EF** [comment]
tier1/mempool.h
class CUtlMemoryPool -> class CMemoryPool

**Comment by Sh1ft0x0EF** [comment]
Regarding KeyValues implementation location...
It requires to link it explicitly if it's not part of tier1 (that's why it was moved to tier1 I guess...)
Dunno if its location should be simply "public/"
Some binaries of 6153 are containing the path to "public/KeyValues.cpp" but they might be untouched since then
And then the file was moved to tier1 and newer versions of other modules were linked with it

**Comment by BlackPhrase** [comment]
I made a decision

All templated code will be using the latest available changes from Source, cause it will be inlined into the codebase so there is no point in downgrading it if the overall behavior won't change and some parts of the codebase did come from modern versions of (Source) SDK and requires newer versions of (tier1) templated code anyway

It should also fix a lot of currently broken code
